### ISSUE TITLE
The AppendToDataStream endpoint is EXTREMLY slow....

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#36] opened 2024-04-21 17:41 UTC
I've updated the Dart unit tests for the data sub-system, and the AppendToDataStream endpoint takes 9-10 seconds for a very simple batch consisting of two measurements.

This can't be true.... And it in any case should work async.....

**Comment by yuanchen233** [comment] 2024-04-25 13:38
This is caused by 'memory consumption issues' mentioned here,
[https://trello.com/c/aw7NESPG/655-memory-leak-of-carpwebservices?search_id=20853748-f5bd-4c46-a4ac-dbc1d66ed533](url)
It is fixed by #32 .

**Comment by xelahalo** [comment] 2024-05-02 11:56
Fixed by #32

**Closed by xelahalo** 2024-05-02 11:56 UTC
Labels: bug, enhancement
